[tool.poetry]
name = "wizwalker"
version = "0.1.0"
description = "Automation bot for wizard101"
authors = ["StarrFox <starrfox6312@gmail.com>"]
license = "GPL-3.0-or-later"
include = ["wizwalker/data/*", "wizwalker/tools/*"]

[tool.poetry.dependencies]
python = "^3.8"
pymem = "^1.2"

[tool.poetry.dev-dependencies]
pyinstaller = "^3.6"
pywin32-ctypes = "^0.2.0"
pefile = "^2019.4.18"

[tool.poetry.scripts]
wizwalker = "wizwalker.__main__:main"
wiz = "wizwalker.utils:quick_launch"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
